Issue 120 - Add new "add image button" to playlist tab
aridevelopment-de/myanimetab pull request #126
Opened 2022-10-03 10:14 UTC by semnim

related issue #120

fixed PR to merge into dev branch

2022-10-05 13:33 UTC, Ari24-cb24 approved these changes
The only thing I notice is that the toolbar is now somewhat empty (I dislike the empty space there). I think a searchbar might be a good element to add to it. You want to add it as well?

2022-10-05 18:10 UTC, semnim commented
Will do in the next days

2022-10-07 13:41 UTC, Ari24-cb24 commented
I just noticed, it seems like your branch originated from master. Try to avoid that in the future as we mainly use dev for development and master for releases 😅

2022-10-09 08:47 UTC, semnim commented
will fix this in the upcoming PR

2022-10-09 16:21 UTC, semnim commented
Edit on this PR:

- is now based off of dev branch
- implemented search bar


**example:**
before search
<img width="1440" alt="grafik" src="https://user-images.githubusercontent.com/82184629/194767910-0d6177ae-a162-432b-8c66-a7f531831da0.png">

**after search**
<img width="1440" alt="grafik" src="https://user-images.githubusercontent.com/82184629/194767836-3ee41b47-08fd-4131-b579-0e7467b50640.png">

2022-10-09 19:19 UTC, Ari24-cb24 requested changes
I really appreciate the effort you did there. There are some small things that should be changed but the main concepts are well-implemented. I also like the recursive search idea as my first thought was just to search throught the current folder.

2022-10-09 19:19 UTC, Ari24-cb24 commented on src/components/settings/playlist_settings/playlistsettingscomponent.module.css
> +}
Currently there is a blue outline when the input is being focussed. If possible, change this to `outline: none` for now as a general color for all outlines isn't implemented yet.

2022-10-09 19:19 UTC, Ari24-cb24 commented on src/utils/use-search.ts
> +export const useSearch = () => {
If possible, rename this function and the file to something more descriptive e.g. use-image-search

2022-10-09 19:19 UTC, Ari24-cb24 commented on src/components/settings/playlist_settings/PlaylistSettingsComponent.tsx
> +					})}
For sake of complying with react guidelines, add a default `null` return value

2022-10-09 19:19 UTC, Ari24-cb24 commented on src/components/settings/playlist_settings/PlaylistSettingsComponent.tsx
> +					})}
For sake of complying with react guidelines, add a default `null` return value

2022-10-09 19:19 UTC, Ari24-cb24 commented on src/components/settings/playlist_settings/PlaylistSettingsComponent.tsx
>  						);
Why do you use Fragments (`<></>`) and the curley braces here? I don't think they are necessary. If possible, remove the return statement and change the map to an implicit arrow function with brackets.

2022-10-09 19:36 UTC, semnim commented
Thanks for the feedback, I've implemented the suggestions.

2022-10-11 09:38 UTC, Ari24-cb24 approved these changes
Sorry for the late response but thanks for the work! Will merge in a second

2022-10-11 09:44 UTC, merged